# Generated by Django 4.2.6 on 2023-10-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_slider_title2"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
